#!/bin/bash
# TODO: Remove the deduplication and go back to using sh instead of bash.
printf "Testing errors..."
./asy -q -sysdir base -noautoplain -debug errortest 2> errors.temp
result=$(diff <(cat errors.temp | uniq) <(cat errors | uniq))
if test "$result" = ""; then
echo PASSED.
else
echo FAILED.
echo "$result"
exit 1
fi
