#!/bin/sh
echo -n "Testing errors..."
./asy -noautoplain -debug errortest 2> errors.temp
result=`diff errors.temp errors`
if [ "$result" = "" ]; then
echo PASSED.
else
echo FAILED.
echo "$result"
exit 1
fi
