set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)

if (OPTIMIZE_LINK_TIME)
    include(CheckIPOSupported)

    check_ipo_supported(RESULT ipo_supported_result LANGUAGES C CXX)

    if (ipo_supported_result)
        set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)
        message(STATUS "Using link-time optimization")
    else()
        message(FATAL_ERROR "Compiler does not support link-time optimization")
    endif()
endif()

if (TARGET_X86_64_V3_OR_HIGHER)
    set(ACCEPTABLE_X86_ARCHITECTURE_FLAGS AMD64 x86 x86_64 i386 i686)
    if (CMAKE_SYSTEM_PROCESSOR IN_LIST ACCEPTABLE_X86_ARCHITECTURE_FLAGS)
        if (MSVC)
            add_compile_options(/arch:AVX2)
        else()
            add_compile_options(-march=x86-64-v3)
        endif()
    else()
        message(WARNING "Target system is not x86-64 system. TARGET_X86_64_V3_OR_HIGHER will not affect compilation.")
    endif()
endif()