initXasyMode();
// This file was generated by xasy. It may be edited manually, however, a strict
// syntax must be followed. It is advised that manually scripted items be added
// in the form of a script either by using xasy or by mimicking the format of an
// xasy-generated script item.
// Please consult the documentation or the examples provided for details.
xformStack.add(indexedTransform(0,(0, 0, 1, 0, 0, 1)),
indexedTransform(1,(0, 0, 1, 0, 0, 1)),
indexedTransform(2,(0, 0, 1, 0, 0, 1)),
indexedTransform(3,(0, 0, 1, 0, 0, 1)),
indexedTransform(4,(0, 0, 1, 0, 0, 1)),
indexedTransform(5,(0, 0, 1, 0, 0, 1)),
indexedTransform(6,(0, 0, 1, 0, 0, 1)),
indexedTransform(7,(0, 0, 1, 0, 0, 1)),
indexedTransform(8,(0, 0, 1, 0, 0, 1)),
indexedTransform(9,(0, 0, 1, 0, 0, 1)),
indexedTransform(10,(0, 0, 1, 0, 0, 1)),
indexedTransform(11,(0, 0, 1, 0, 0, 1)),
indexedTransform(12,(0, 0, 1, 0, 0, 1)));
startScript(); {
size(0,150);

pen colour1=red;
pen colour2=green;

pair z0=(0,0);
pair z1=(-1,0);
pair z2=(1,0);
real r=1.5;
guide c1=circle(z1,r);
guide c2=circle(z2,r);
fill(c1,colour1);
fill(c2,colour2);

picture intersection;
fill(intersection,c1,colour1+colour2);
clip(intersection,c2);

add(intersection);

draw(c1);
draw(c2);

label("$A$",z1);
label("$B$",z2);

pair z=(0,-2);
real m=3;
margin BigMargin=Margin(0,m*dot(unit(z1-z),unit(z0-z)));

draw(Label("$A\cap B$",0),conj(z)--z0,Arrow,BigMargin);
draw(Label("$A\cup B$",0),z--z0,Arrow,BigMargin);
draw(z--z1,Arrow,Margin(0,m));
draw(z--z2,Arrow,Margin(0,m));
} endScript();


xformStack.push((-28.0, 7.0, 1, 0, 0, 1));
label(Label("A Venn Diagram",(-79.0, 91.0),rgb(0,0,0)+0.5,align=SE));

// This is the end of the file
exitXasyMode();

