.\"                                      Hey, EMACS: -*- nroff -*-
.TH ASY 1 "1 Dec 2004"
.SH NAME
asy \- Asymptote: a script-based vector graphics language
.SH SYNOPSIS
.B asy
.RI [ options ] [ file ... ]
.SH DESCRIPTION
\fBAsymptote\fP is a powerful script-based vector graphics language for
technical drawings, inspired by MetaPost but with an improved C++\-like syntax.
Asymptote provides for figures the same high\-quality level of typesetting that
LaTeX does for scientific text.
.SH OPTIONS
If no arguments are given, Asymptote runs in interactive mode.
.PP
If "-" is given as the file argument, Asymptote reads from standard input.
.PP
A summary of options is included below. The effect of most options
can be negated by prepending 
.B no
to the option name. 
Default values for most options may also be entered in the 
file 
.B .asy/config.asy
in the user's home directory using the long form:
.PP
import settings;
.PP
batchView=true;
.PP
For a complete
description, see the Info files.
.TP
.B -V, -View
View output file.
.TP
.B -a, -align C|B|T|Z
Center, Bottom, Top or Zero page alignment; Z => -notex.
.TP
.B -autoplain
Enable automatic importing of plain (default).
.TP
.B -batchMask
Mask fpu exceptions in batch mode.
.TP
.B -batchView
View output files in batch mode.
.TP
.B -bw
Convert all colors to black and white.
.TP
.B -c, -clearGUI
Clear GUI operations.
.TP
.B -cmyk
Convert rgb colors to cmyk.
.TP
.B -d, -debug
Enable debugging messages.
.TP
.B -x, -deconstruct X
Deconstruct into transparent GIF objects magnified by X.
.TP
.B -gray
Convert all colors to grayscale.
.TP
.B -h, -help
Show summary of options.
.TP
.B -historylines n 
Retain n lines of history (default 1000).
.TP
.B -i, -ignoreGUI
Ignore GUI operations.
.TP
.B -interactiveMask
Mask fpu exceptions in interactive mode.
.TP
.B -interactiveView
View output files in interactive mode.
.TP
.B -k, -keep
Keep intermediate files.
.TP
.B -l, -listvariables
List available global functions and variables.
.TP
.B -localhistory
Use a local interactive history file.
.TP
.B -m, -mask
Mask fpu exceptions.
.TP
.B -O,-offset pair
PostScript offset.
.TP
.B -f, -outformat format
Convert each output file to specified format.
.TP
.B -o, -outname name
(First) output file name.
.TP
.B -p, -parseonly
Parse test.
.TP
.B -rgb
Convert cmyk colors to rgb.
.TP
.B -safe
Disable system call (default).
.TP
.B -tex
Enable LaTeX label postprocessing (default).
.TP
.B -s, -translate
Translate test.
.TP
.B -unsafe
Enable system call.
.TP
.B -v, -verbose
Increase verbosity level.

.SH SEE ALSO
Asymptote is documented fully in the asymptote Info page.
The manual can also be accessed in interactive mode with the "help" command.

.SH AUTHOR
Asymptote was written by Andy Hammerlindl, John Bowman, and Tom Prince.
.PP
This manual page was written by Hubert Chan for the Debian project (but may
be used by others).
