(load-file "/usr/local/share/asymptote/asy-mode.el")
(asy-mode)
(indent-region (point-min) (point-max) nil)
(untabify (point-min) (point-max))
(delete-trailing-whitespace (point-min) (point-max))
(save-buffer)
