#!/bin/sh -x
#Be sure to remove /usr/include/GL
wget http://prdownloads.sourceforge.net/freeglut/freeglut-2.8.1.tar.gz
ln -sf /usr/bin/cyggcc_s-1.dll /usr/lib/libgcc_s.a
tar -zxf freeglut-2.8.1.tar.gz
cd freeglut-2.8.1
patch -p1 < ~/asymptote/patches/cygwin_freeglut-2.8.1.patch
./configure --prefix=/usr --without-x
make
cd src
gcc -s -static -shared -o freeglut.dll *.o -Wl,--out-implib=libfreeglut.a -lglu32 -lopengl32 -lgdi32 -lwinmm
cp freeglut.dll /lib
mkdir -p ~/dll
cp freeglut.dll ~/dll
gcc -s -shared -o freeglut.dll *.o -Wl,--out-implib=libfreeglut.a -lglu32 -lopengl32 -lgdi32 -lwinmm
cp libfreeglut.a /lib
cd ..
cp -a include/GL/*.h /usr/include/w32api/GL/

#OPTIONAL: To compile manually in src:
#gcc -O2 -c -D_WIN32 -DHAVE_CONFIG_H -DFREEGLUT_EXPORTS *.c -I.. -I../include

