#!/bin/sh
if [ ! $# = 1 ]; then echo Usage: "$0 AsyGLVersion"; exit 1; fi
GL_MATRIX_VERSION=2.8.1
GL_MATRIX_DIR=gl-matrix-$GL_MATRIX_VERSION
if test ! -r $GL_MATRIX_DIR; then \
    TEMPDIR=`mktemp -d`
    TARFILE=$TEMPDIR/$GL_MATRIX_DIR.tar.gz
    wget https://github.com/toji/gl-matrix/archive/v$GL_MATRIX_VERSION.tar.gz --output-document=$TARFILE
tar -zxf $TARFILE
rm -r $TEMPDIR
fi
sed -e 's|\/\*!|/*@license|' $GL_MATRIX_DIR/dist/gl-matrix-min.js webgl/gl.js | uglifyjs -m -c -o base/webgl/asygl-$1.js --comments
